package requireannotationsonsupertype;

@RequireUnconstrainedSupertype
public class RequireAnnotationsOnSupertypeIndirectPass extends ExtendsUnconstrainedClass implements RequireUnconstrainedInterface {
}
